version: "3.8"

services:
  db:
    image: postgres:15.5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: 5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
    - redis_data:/var/lib/redis/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_NAME: ${DB_NAME}

    ports:
      - 3000:3000
    command: ./bin/rails server -p 3000 -b 0.0.0.0
    environment:
      DATABASE_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"

    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:


